env:
  map_path: maps/8x8/basesWorkers8x8.xml
  max_steps: 2000
  interval: 200
  record_video: true
  display: false

agents:
  - model: sap_agent
    temperature: 0
    max_tokens: 8192
    strategy_interval: 200
    prompt: zero-shot-messages
  - model: Qwen2.5-72B-Instruct
    temperature: 0
    max_tokens: 8192
    prompt: few-shot-w-strategy
    strategy: randomAI

episodes: 3
